# While a lot of configuration in Sentry can be changed via the UI, for all
# new-style config (as of 8.0) you can also declare values here in this file
# to enforce defaults or to ensure they cannot be changed via the UI. For more
# information see the Sentry documentation.

###############
# Mail Server #
###############

# mail.backend: 'smtp'  # Use dummy if you want to disable email entirely
mail.host: 'smtp'
# mail.port: 25
# mail.username: ''
# mail.password: ''
# mail.use-tls: false
# The email address to send on behalf of
# mail.from: 'root@localhost'

# If you'd like to configure email replies, enable this.
# mail.enable-replies: true

# When email-replies are enabled, this value is used in the Reply-To header
# mail.reply-hostname: ''

# If you're using mailgun for inbound mail, set your API key and configure a
# route to forward to /api/hooks/mailgun/inbound/
# Also don't forget to set `mail.enable-replies: true` above.
# mail.mailgun-api-key: ''

###################
# System Settings #
###################

# If this file ever becomes compromised, it's important to generate a new key.
# Changing this value will result in all current sessions being invalidated.
# A new key can be generated with `$ sentry config generate-secret-key`
system.secret-key: 'a-really-long-secret-value'

# The ``redis.clusters`` setting is used, unsurprisingly, to configure Redis
# clusters. These clusters can be then referred to by name when configuring
# backends such as the cache, digests, or TSDB backend.
# redis.clusters:
#   default:
#     hosts:
#       0:
#         host: 127.0.0.1
#         port: 6379

################
# File storage #
################

# Uploaded media uses these `filestore` settings. The available
# backends are either `filesystem` or `s3`.

filestore.backend: 'filesystem'
filestore.options:
  location: '/data/files'
dsym.cache-path: '/data/dsym-cache'
releasefile.cache-path: '/data/releasefile-cache'

# filestore.backend: 's3'
# filestore.options:
#   access_key: 'AKIXXXXXX'
#   secret_key: 'XXXXXXX'
#   bucket_name: 's3-bucket-name'

system.internal-url-prefix: 'https://sentry.isteer.com'
symbolicator.enabled: true
symbolicator.options:
  url: "http://symbolicator:3021"

transaction-events.force-disable-internal-project: true

######################
# GitHub Integration #
######################

# github-login.extended-permissions: ['repo']
github-app.id: 112633
github-app.name: 'onpremise2'
github-app.webhook-secret: '025a5f2b0eadee6a57169bdaaf7be2300555ca97' # Use only if configured in Git
github-app.client-id: 'Iv1.7f03655b88aea38d'
github-app.client-secret: '61d8e3d7ba5ae146fa33d36377cd21d5f828d9a6'
github-app.private-key: "-----BEGIN RSA PRIVATE KEY-----\n
MIIEowIBAAKCAQEA1MJrUmJXMQTpe8lEE6OJ08Dxs1ymYOfu+5OAXAno08Pr8dN8\n
wNL3n1TAIXGbxlnCY71aWi8poestP5pO+sG4yGPzAVADpXgUHgmymVI/qOCW/jo/\n
31lHO1GGXQXevQ3wRdD4mMZR3zcC9nM6WkiBTWoa242mzQ2jnqeQReSaRgsOEkDi\n
O4jWE7iqr1hYBTSBCHQSXLLyLlWIJZTLmSEzhdUXJ6XGr6Yeq7VwfxfLmV4/x4M9\n
R0gHLyw4mpFQNAPuhJ2rro4jcSP5NQaXSjBjvjp9LuYmabrZ9UpbJ0avkjpQsYDV\n
/T1o9CUmmaU4rRbRD9Gl9GUYk4aJmcCOZbz3TwIDAQABAoIBAGRl8lsICPkaxksh\n
qLxTueBw9h2bpO+pwv54lmPYUURM+fQ9xmr/otZPGfMuN0IcbTy/x/kytESyQ8H1\n
wTtXWylE8RE3fuEAjw21qc/sHhpFETuapTVyXcjCKdOPx5ITF8T6XbVKMKxSu1Us\n
/uZHvKyZW18rswCkZQejLtOskphmFtRsoTcxEqfWisq9QnWQErp53iqHvWW99Gaj\n
tMDDNCNbp78NPIZc0EePLTgFeYLmV+K0/CO98ISh4xOvDpI7+bB8ug5cmdc/9o6l\n
2fM6/nolAtgfJrBoF3E0b7zjVE0zKX81tbWQ+hDEp0jHZ3+q1uE7U/29WXopN8e0\n
OBWQDZECgYEA6lWQhqDUPA5zhpi5cfWJIZ9dqxgrNAug7psRWlajMvJNPszmNkdq\n
JzblG3IU/p5aK6Sl3mG9dOnkLabaraC2eAYKjgGC70LzlNynWsH/RC1GjbXcD0/Q\n
ZNdJ4cYGvImPb59JN/AQ7pq9ScmxC2iI92z9I0Ic39CXZo0c635ZVM0CgYEA6G4z\n
+myUPJKts4QR1aoQIMJmek2rdC+O2gl2FkhWMeyNVRysS/xpq+SrE1kcjHGJ/aUZ\n
zvBzaGnIhFuuiYhWle4GG2Hb7475mCjJprYClnncqqQ/7CjXs4E0TVS1VeqXH13z\n
CUnT9To1e7fX1M1VhfaVW28jSuTZ1I0pJJHLnIsCgYAKjEtzI+4pveTJXDqMvKat\n
ksTenLnlH9jgpK5FSL0T4ABGIWcDbneCyF/LunjjdTFN4Z1twyyKBLU2sNoLEr7j\n
7DGxbrP8HSFlxADsfusEoJ0aZ+M99TPGNkKnHQjUl8STG7JqCC5a7zAyEBgeEViI\n
+qjyW1l9YaBPB28T0p4myQKBgGJK8HpP3qR7FzAagvxLrgRckb/ZBs/cqNm2NJUZ\n
xDHaqq46sPZ1aS7DRkGpZrRR85wrbO2hq/yU97JZn0cUPCGthjGgQcVePllFrnls\n
8U03fcVALrQtVYLY+ghV8VXDHmOqdHQSH6vOEP4f8gtRRoCflewT5OXwP9puU97e\n
NTAfAoGBAM9Jdy6F19d0BB+/aWofUSDP9Jlp/FiHZEkDk7ZGrMGAbatmrGpX5fgD\n
hKBULCMQWV6MSGflo2k8dlgsDkpbsNAtK5j0FSXiVxunZA97GQFXOdpHdGmLDKFs\n
HnsNSEzEkvyBpPcF4VRbIYufXHCkUgu2XQBvEBXlz/Wy/qWdn56k\n
-----END RSA PRIVATE KEY-----\n"

#####################
# Slack Integration #
#####################

# Refer to https://develop.sentry.dev/integrations/slack/ for setup instructions.

# slack.client-id: <'client id'>
# slack.client-secret: <client secret>
# slack.signing-secret: <signing secret>
## If legacy-app is True use verfication-token instead of signing-secret
# slack.verification-token: <verification token>

# Azure DevOps #
vsts.client-id: '128EE93F-10D3-495B-A947-D0CE7DAE77C9'
vsts.client-secret: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im9PdmN6NU1fN3AtSGpJS2xGWHo5M3VfVjBabyJ9.eyJjaWQiOiIxMjhlZTkzZi0xMGQzLTQ5NWItYTk0Ny1kMGNlN2RhZTc3YzkiLCJjc2kiOiI4ODI1MjQ4ZS1kMjQ5LTRhMzUtODhiZC0xNTBjMGEzYzA5ZGEiLCJuYW1laWQiOiI3Yjc3YWFkNC0yNDY1LTYwMjUtOTg1Ni1kZTUxNzZlMmE2YmQiLCJpc3MiOiJhcHAudnN0b2tlbi52aXN1YWxzdHVkaW8uY29tIiwiYXVkIjoiYXBwLnZzdG9rZW4udmlzdWFsc3R1ZGlvLmNvbSIsIm5iZiI6MTYxOTUwMzEyNywiZXhwIjoxNzc3MjY5NTI3fQ.EbqEPej4KUFrQt-2cx7edLPQvdiYtUkjMgodFW4mLmg5uwdIVQXpDU6NevjfD1yFcJKKGYH51Do1Eyv9FN2EcF7qHeFWBrcjSKH5d_tEYzGBnsRNQG-H6s4YFEKmGCclO0AbAOhibbpgKa_PvTKkCcJbXFuitrWQc6WuDPiZRvy-l8Lt7MTYl8mMcm5LgAqjeD-1Y-z77Z03lxvKozUg01JPenNHZcHawkrB7-LhO6NS4-Y4Y2cJVZlT0KRWz8_4qG0bdG_tOuteOvWvIaaUWLWBycGP6OMOnM3nKdlTY8I0xaU35iJ5yWm_KYnl-lPR3W7gWvcI-Ru6xx0Ud573Hg'



# google auth credentials #

auth-google.client-id: '610704846999-6ca37t734vripgqj9d81ncaee9sdn4sf.apps.googleusercontent.com'
auth-google.client-secret: 'hLcEK2wrse-gIsTDJM4j0uSP'