# While a lot of configuration in Sentry can be changed via the UI, for all
# new-style config (as of 8.0) you can also declare values here in this file
# to enforce defaults or to ensure they cannot be changed via the UI. For more
# information see the Sentry documentation.

###############
# Mail Server #
###############

# mail.backend: 'smtp'  # Use dummy if you want to disable email entirely
mail.host: 'smtp'
# mail.port: 25
# mail.username: ''
# mail.password: ''
# mail.use-tls: false
# The email address to send on behalf of
# mail.from: 'root@localhost'

# If you'd like to configure email replies, enable this.
# mail.enable-replies: true

# When email-replies are enabled, this value is used in the Reply-To header
# mail.reply-hostname: ''

# If you're using mailgun for inbound mail, set your API key and configure a
# route to forward to /api/hooks/mailgun/inbound/
# Also don't forget to set `mail.enable-replies: true` above.
# mail.mailgun-api-key: ''

###################
# System Settings #
###################

# If this file ever becomes compromised, it's important to generate a new key.
# Changing this value will result in all current sessions being invalidated.
# A new key can be generated with `$ sentry config generate-secret-key`
system.secret-key: '!!changeme!!'

The ``redis.clusters`` setting is used, unsurprisingly, to configure Redis
clusters. These clusters can be then referred to by name when configuring
backends such as the cache, digests, or TSDB backend.
redis.clusters:
  default:
    hosts:
      0:
        host: 127.0.0.1
        port: 6379

################
# File storage #
################

# Uploaded media uses these `filestore` settings. The available
# backends are either `filesystem` or `s3`.

filestore.backend: 'filesystem'
filestore.options:
  location: '/data/files'
dsym.cache-path: '/data/dsym-cache'
releasefile.cache-path: '/data/releasefile-cache'

# filestore.backend: 's3'
# filestore.options:
#   access_key: 'AKIXXXXXX'
#   secret_key: 'XXXXXXX'
#   bucket_name: 's3-bucket-name'

system.internal-url-prefix: 'https://sentry.isteer.com'
symbolicator.enabled: true
symbolicator.options:
  url: "http://symbolicator:3021"

transaction-events.force-disable-internal-project: true

######################
# GitHub Integration #
######################

# github-login.extended-permissions: ['repo']
github-app.id: 111982
github-app.name: 'onpremise1'
github-app.webhook-secret: 'bdeff92bbb2a2cb7134a53b12e4586185b835c6b' # Use only if configured in Git
github-app.client-id: 'Iv1.b3973cf27fb143f4'
github-app.client-secret: '5a54ad470a50fbcda05b6fbf485adae517696771'
github-app.private-key: 'MIIEowIBAAKCAQEA43ibPVO/3NWylSndacCnWDZ5B4TwtxRxgkNg2RmMrOIYL3hY yiWWVtoYdXJQ/hUacurQ5ttPd3jjBrxUNA27io+ekrMiIJryte4lss2igY2UJXQl rjx3wsoZ8aFuAVm0zbStpQExhd2SbzqDVmwRY5WGCKxnizo4GZiQWfV1MUWJZtP7 M0C1nO5Ltmf4xOgsblB82jFkeONfLzT6LwlMKP3v85H1NnPbFMUokl8tzaUNf5B0 g/6L+dAbQHdvkYcE6M+iG8fNfEVtFWXrC55EVbUR0GpBoDkmjNhVH/HXlVqRpVC3 ps4Q7xuDl39nHbsVcTDjQO9PuL/VFLTvXdabqQIDAQABAoIBAQCDuhQsL5OsDxSb zOKrmyVNsD3mXNYJL42MIfizwFf2xfe7hbXlWl71bNc9LDY67X2jjtfq2JXsWdUe 0XDxtAIm+4SY76OTvidPs9mg8fRpkdN43Qn1HI89/kuH4jQSFCDf/wGPzGEhZG6o evoT0gE/6hb0buKHfe9+4xq0/bAgF0zvQ5EQ+xjt7qZQjHthuRoUrfSFwfuMJppj MNUiGy7vS0azkhSsS8fjBZOtdXfqIbnOta4WNb1KDaJkT4rvzEErI2Oc0Et3MwnB QSLQ+NKaSriXveCwHV+McZHuEv+TMdmDRscnH6Av3f93jOVoJeZluKM7lDlPj9Ly 1nVHglEBAoGBAPzQI5FHKpPzSqX5a1vAHFkkvrAd2EPnPlfWkAETk6D28zYiMwFt Rp+eSmI+5xzMpi259CbYVG39BDQ4xFb/vfOltxkgQtiAntN/dfAqe/I4v0oUTLDe YVLIZr2pJKmvA7fl3U1wClbZhPWFSXvz4N7r0Zg+70uSQwPGsI70q+IbAoGBAOZW r4xR4uhmrJOcsrYtdDfIAR36k9R+a1oqzuZqkS7LVejhm8RPN6xA24n5nPDYPheR Ddzqc5dMJ/y1xVcrvz1al8m8kn/w3kiBJGeL5u/80PVDTYkbpoHktLuDgORAqd4j Y18cmc1oDj/JmeDgYvb7cxdIbOFfaSh9qCc5TfWLAoGAFixbMj6/qUJJZc0+cUmk Mt1aLDAx66K4gRO8hZul8xQ1uKW/O3zOGOnVNFC4DHqWiKQqmc2Xeh4a5EmmTssX aes65+VAd6SwSXSAb5QKUvBPNrwZDdozRwN0n2XaZVeIR/TNOCF/hqaFVtNd4pU9 P9AHDgdXDZXCcu5WRfOHr8kCgYAlpS9FuLBkGTvFWEvg+GbRIxADrUtx5EN5VhvA jtQxmKvuxsileej4bxUyZKhguIbVZTCl1W+U3659X9vj1lOIHIFISFiNLnm10d14 SuYwfNpN63UFno5FFnLvXpu3MlZQ5um7xrngV0xU4ocSuLmT8h6qRHz/DI/sPTU5 S+VQ5wKBgEXiAJDlbbrJ6H/gFqos15xq5m2i8MpFtckgAt1H/B2zZtJEp2CQkdXK c48rdzR0QsilTDvtbmGbUkePT+NFJMWU152iolSh7eIzeiL6AIfvjGITd/XxmDSZ rxrGum+nyevh33KiICoYmCC4vcdKH9M5QrAuWBeH70GEkO2RVt0l'

#####################
# Slack Integration #
#####################

# Refer to https://develop.sentry.dev/integrations/slack/ for setup instructions.

# slack.client-id: <'client id'>
# slack.client-secret: <client secret>
# slack.signing-secret: <signing secret>
## If legacy-app is True use verfication-token instead of signing-secret
# slack.verification-token: <verification token>

# Azure DevOps #
vsts.client-id: 'C3578C57-BA4E-48EC-84B1-32AE629F74ED'
vsts.client-secret: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im9PdmN6NU1fN3AtSGpJS2xGWHo5M3VfVjBabyJ9.eyJjaWQiOiJjMzU3OGM1Ny1iYTRlLTQ4ZWMtODRiMS0zMmFlNjI5Zjc0ZWQiLCJjc2kiOiJmMWUzNzkyZC0wMmY1LTQ0NTEtODkwNS05NjE2MzYzNTUxOTQiLCJuYW1laWQiOiI3Yjc3YWFkNC0yNDY1LTYwMjUtOTg1Ni1kZTUxNzZlMmE2YmQiLCJpc3MiOiJhcHAudnN0b2tlbi52aXN1YWxzdHVkaW8uY29tIiwiYXVkIjoiYXBwLnZzdG9rZW4udmlzdWFsc3R1ZGlvLmNvbSIsIm5iZiI6MTYxOTE2NDc1MywiZXhwIjoxNzc2OTMxMTUzfQ.m1HzPoO2VMGtaQhKRdMuQIHOOeULYtBdmv5UXoLgUuvUOdvLmH8TSnCmE66Zz-0jkrUVZcQbNkmcieNSrOT5Hth9F972FINya_FagriOle0hNfoA2EjdvlzNQT53zhAzVkC1pIARC-GRRWDoeawaSkr60Jpkct54dgjTZOjYKfJClfJPmJxI1I7oo-oOTeBNLaWfBNHz-_jTNoipSWjiRPqT_nscIVGSuU5d7WJYQZKqds91gpSBwjounITLU4HGvFA2McE0yAEV3dHNqfDq3afF2M9CpoQObzUpOIjB41pXChmB_X_mgtfv4xiq0mvJcpf12kREd5A1559ncbCu5g'



# google auth credentials #

auth-google.client-id: '610704846999-8gokvno1aqfjmf07futncdn5kno3ihel.apps.googleusercontent.com'
auth-google.client-secret: 'Ic2PyyOVBO_uvPFCVRMb7tm2'