# While a lot of configuration in Sentry can be changed via the UI, for all
# new-style config (as of 8.0) you can also declare values here in this file
# to enforce defaults or to ensure they cannot be changed via the UI. For more
# information see the Sentry documentation.

###############
# Mail Server #
###############

# mail.backend: 'smtp'  # Use dummy if you want to disable email entirely
mail.host: 'smtp'
# mail.port: 25
# mail.username: ''
# mail.password: ''
# mail.use-tls: false
# The email address to send on behalf of
# mail.from: 'root@localhost'

# If you'd like to configure email replies, enable this.
# mail.enable-replies: true

# When email-replies are enabled, this value is used in the Reply-To header
# mail.reply-hostname: ''

# If you're using mailgun for inbound mail, set your API key and configure a
# route to forward to /api/hooks/mailgun/inbound/
# Also don't forget to set `mail.enable-replies: true` above.
# mail.mailgun-api-key: ''

###################
# System Settings #
###################

# If this file ever becomes compromised, it's important to generate a new key.
# Changing this value will result in all current sessions being invalidated.
# A new key can be generated with `$ sentry config generate-secret-key`
system.secret-key: 'a-really-long-secret-value'

# The ``redis.clusters`` setting is used, unsurprisingly, to configure Redis
# clusters. These clusters can be then referred to by name when configuring
# backends such as the cache, digests, or TSDB backend.
# redis.clusters:
#   default:
#     hosts:
#       0:
#         host: 127.0.0.1
#         port: 6379

################
# File storage #
################

# Uploaded media uses these `filestore` settings. The available
# backends are either `filesystem` or `s3`.

filestore.backend: 'filesystem'
filestore.options:
  location: '/data/files'
dsym.cache-path: '/data/dsym-cache'
releasefile.cache-path: '/data/releasefile-cache'

# filestore.backend: 's3'
# filestore.options:
#   access_key: 'AKIXXXXXX'
#   secret_key: 'XXXXXXX'
#   bucket_name: 's3-bucket-name'

system.internal-url-prefix: 'https://sentry.isteer.com'
symbolicator.enabled: true
symbolicator.options:
  url: "http://symbolicator:3021"

transaction-events.force-disable-internal-project: true

######################
# GitHub Integration #
######################

github-login.extended-permissions: ['repo']
github-app.id: 111982
github-app.name: 'onpremise1'
github-app.webhook-secret: 'bdeff92bbb2a2cb7134a53b12e4586185b835c6b' # Use only if configured in Git
github-app.client-id: 'Iv1.b3973cf27fb143f4'
github-app.client-secret: '5a54ad470a50fbcda05b6fbf485adae517696771'
github-app.private-key: "-----BEGIN RSA PRIVATE KEY-----\n
MIIEogIBAAKCAQEAtaxSZkWXwd3PvD64fvhJ5EE+/MQW0tRwZFM5JlP/JMFxdjRo\n
RXyAvDfrwoehOFs8EdsLoooymhmxgixDTadjztIOqEDEJF+Vbjxn94QwZVxJKWf6\n
+HDd4NrYrMU5OtUQ9i92W8L2DnlbIFOfSfmOfQIKRQ1FEAOQMUN0aTPQMTnXL3Gs\n
zezyJmkQSBDnp/sJSE4pEqVVLxhTHIvIhoIFxQNYNS2P8DOSplJgOhPjP/61sv9V\n
Gu7gTMGQHc+ia9X1Bdb42j0aRhHP/zVt153V48X/Sqm1MxEF99Vp8xJd+LSuWzy6\n
vd+Hy/cPyjhf2CI0/xstdaFtVWPsbJKbIVrCNwIDAQABAoIBADl9bZnlne+AhNN6\n
OaIcai2sJAWS+/H9vg9Rcr1ZSV1VRdV1IiYTDx4AyD+H8hHGdUzlN1pZR0gSp2Sd\n
IzM4rFHvkSnXTPqBsOTwgqoGD9aTjKdouzfRZ7VXK8gIpWKjuDlfraG+IWVVK+wf\n
6kFbkqamdZ+CYn990Sx1vynndpOMw/FMkR0u9Ty4LH2HRwbXBl1vksRBvsKT7hkg\n
cA332oD0dDEKa8va5xDanG0si8BHPoUpdeSx1haiGnXzUgZVvlJTuaNX2Hs6kNop\n
5d1xY/5ORQMB1/QafNJcCW2ABedNEf94Y1Qbk+oYaZGYnOwdKtweZp9XFz5Kfs61\n
Wk6u6AECgYEA7/0oEExrbrNzirdTavGvfQ2v9IWkBoFjGbT2Y6/RkZ3Z1GxRTppD\n
1qTkGrGKturvFhgQ4gJ4N37nlDdpIwy7xtyo0mBdPRHGcI+P3KU8Vvg53dsGfzpr\n
YPYuQudr4sUdRxYjIWSh6qrQotZok1WfBSw00WmGhk0dyCqw4sB/tAECgYEAwcss\n
Nyc78CdC4Nom9XiQCp/v+ydfG75gQLx3RcbBIwgBt10XMwaUz2zwDUXEn04yqG0S\n
+XghzDzVRHgV8Qz4B2zDNAdg/ub1mBXo4/Iwf1sbtfqk1zhfhRMfDSdbVsh1hy8/\n
HVXyLhNVT9VCIkp4VjwHkV0fIRS4SM4bOvBzFjcCgYAaYGWd3PhV021YiqulbmjO\n
QsnbAzEy8deVhLkr3bAX5BSD71/EVtor5jWX5XmMfyfF8uEwJftWhiEnvitVCdo9\n
khUQAj1dL+3ygyTZqGOIX4Hkq2T8aMxSfNw6yDqoUufT30//JJNTOnDx5MTbpKZ0\n
qBYqCgIaErG6RU7prSScAQKBgGI4V3CcsgRF4d+Usao4MMkxxq/EhK/LDX3CB7GV\n
ys22gSguRlPWQhXfYMtZUQ5s08AJiFRoTrj1HCJXuscxi4Q327fDBaYr6M3sTN07\n
Itlpk+Hn5yQtrjwENPi1udWCRA8AIzz7EoPHyLVtoNdAZz1Nr4g9akmZ9szvqV12\n
AN6BAoGADUWNpjod8MGu7YhJ5HJ1FzHQxWCa+Bcbx10ydPfQaTOtYG8ZjuVYOJkt\n
Cu/9z6ebXSD5dzanAIp76lXvjTD9e+hJCGtAdXxA9Lxu1e0kiWVihXIL+mq4Wm8z\n
6FpagYc3nA/sHlMSC5lAsAqo/ALhveVvj64nauCY+Ep4eMJDZT4=\n
-----END RSA PRIVATE KEY-----\n"

#####################
# Slack Integration #
#####################

# Refer to https://develop.sentry.dev/integrations/slack/ for setup instructions.

# slack.client-id: <'client id'>
# slack.client-secret: <client secret>
# slack.signing-secret: <signing secret>
## If legacy-app is True use verfication-token instead of signing-secret
# slack.verification-token: <verification token>

# Azure DevOps #
vsts.client-id: '128EE93F-10D3-495B-A947-D0CE7DAE77C9'
vsts.client-secret: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im9PdmN6NU1fN3AtSGpJS2xGWHo5M3VfVjBabyJ9.eyJjaWQiOiIxMjhlZTkzZi0xMGQzLTQ5NWItYTk0Ny1kMGNlN2RhZTc3YzkiLCJjc2kiOiI4ODI1MjQ4ZS1kMjQ5LTRhMzUtODhiZC0xNTBjMGEzYzA5ZGEiLCJuYW1laWQiOiI3Yjc3YWFkNC0yNDY1LTYwMjUtOTg1Ni1kZTUxNzZlMmE2YmQiLCJpc3MiOiJhcHAudnN0b2tlbi52aXN1YWxzdHVkaW8uY29tIiwiYXVkIjoiYXBwLnZzdG9rZW4udmlzdWFsc3R1ZGlvLmNvbSIsIm5iZiI6MTYxOTUwMzEyNywiZXhwIjoxNzc3MjY5NTI3fQ.EbqEPej4KUFrQt-2cx7edLPQvdiYtUkjMgodFW4mLmg5uwdIVQXpDU6NevjfD1yFcJKKGYH51Do1Eyv9FN2EcF7qHeFWBrcjSKH5d_tEYzGBnsRNQG-H6s4YFEKmGCclO0AbAOhibbpgKa_PvTKkCcJbXFuitrWQc6WuDPiZRvy-l8Lt7MTYl8mMcm5LgAqjeD-1Y-z77Z03lxvKozUg01JPenNHZcHawkrB7-LhO6NS4-Y4Y2cJVZlT0KRWz8_4qG0bdG_tOuteOvWvIaaUWLWBycGP6OMOnM3nKdlTY8I0xaU35iJ5yWm_KYnl-lPR3W7gWvcI-Ru6xx0Ud573Hg'



# google auth credentials #

auth-google.client-id: '610704846999-6ca37t734vripgqj9d81ncaee9sdn4sf.apps.googleusercontent.com'
auth-google.client-secret: 'hLcEK2wrse-gIsTDJM4j0uSP'